[package]
name = "wstcp"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
bytecodec = "0.2"
byteorder = "1"
clap = "2"
fibers = "0.1"
futures = "0.1"
httpcodec = {path = "../httpcodec/"}
slog = "2"
sloggers = "0.2"
trackable = "0.2"
