[package]
name = "wstcp"
version = "0.1.5"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "WebSocket to TCP proxy server"
homepage = "https://github.com/sile/wstcp"
repository = "https://github.com/sile/wstcp"
readme = "README.md"
keywords = ["websocket", "proxy", "tcp"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = {repository = "sile/wstcp"}

[dependencies]
base64 = "0.12"
bytecodec = "0.4"
byteorder = "1"
clap = "2"
fibers = "0.1"
futures = "0.1"
httpcodec = "0.2"
sha-1 = "0.8"
slog = {version = "2", features = ["release_max_level_debug"]}
sloggers = "0.3"
trackable = "0.2"
